/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'administration-docker-events': RouteRecordInfo<'administration-docker-events', '/administration/docker-events', Record<never, never>, Record<never, never>>,
    'administration-manage-flux': RouteRecordInfo<'administration-manage-flux', '/administration/manage-flux', Record<never, never>, Record<never, never>>,
    'administration-manage-users': RouteRecordInfo<'administration-manage-users', '/administration/manage-users', Record<never, never>, Record<never, never>>,
    'administration-system-info': RouteRecordInfo<'administration-system-info', '/administration/system-info', Record<never, never>, Record<never, never>>,
    'apps-global': RouteRecordInfo<'apps-global', '/apps/global', Record<never, never>, Record<never, never>>,
    'apps-local': RouteRecordInfo<'apps-local', '/apps/local', Record<never, never>, Record<never, never>>,
    'apps-manage-app-name': RouteRecordInfo<'apps-manage-app-name', '/apps/manage/:appName', { appName: ParamValue<true> }, { appName: ParamValue<false> }>,
    'apps-management': RouteRecordInfo<'apps-management', '/apps/management', Record<never, never>, Record<never, never>>,
    'apps-register': RouteRecordInfo<'apps-register', '/apps/register', Record<never, never>, Record<never, never>>,
    'apps-register-configure': RouteRecordInfo<'apps-register-configure', '/apps/register/configure', Record<never, never>, Record<never, never>>,
    'checkout-gateway-plan': RouteRecordInfo<'checkout-gateway-plan', '/checkout/:gateway/:plan', { gateway: ParamValue<true>, plan: ParamValue<true> }, { gateway: ParamValue<false>, plan: ParamValue<false> }>,
    'cost-calculator': RouteRecordInfo<'cost-calculator', '/cost-calculator', Record<never, never>, Record<never, never>>,
    'dashboards-home': RouteRecordInfo<'dashboards-home', '/dashboards/home', Record<never, never>, Record<never, never>>,
    'dashboards-list': RouteRecordInfo<'dashboards-list', '/dashboards/list', Record<never, never>, Record<never, never>>,
    'dashboards-locations': RouteRecordInfo<'dashboards-locations', '/dashboards/locations', Record<never, never>, Record<never, never>>,
    'dashboards-overview': RouteRecordInfo<'dashboards-overview', '/dashboards/overview', Record<never, never>, Record<never, never>>,
    'dashboards-resources': RouteRecordInfo<'dashboards-resources', '/dashboards/resources', Record<never, never>, Record<never, never>>,
    'dashboards-rewards': RouteRecordInfo<'dashboards-rewards', '/dashboards/rewards', Record<never, never>, Record<never, never>>,
    'flux-drive': RouteRecordInfo<'flux-drive', '/flux-drive', Record<never, never>, Record<never, never>>,
    'marketplace': RouteRecordInfo<'marketplace', '/marketplace', Record<never, never>, Record<never, never>>,
    'marketplace-id': RouteRecordInfo<'marketplace-id', '/marketplace/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'marketplace-games': RouteRecordInfo<'marketplace-games', '/marketplace/games', Record<never, never>, Record<never, never>>,
    'marketplace-games-name': RouteRecordInfo<'marketplace-games-name', '/marketplace/games/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    'marketplace-wordpress': RouteRecordInfo<'marketplace-wordpress', '/marketplace/wordpress', Record<never, never>, Record<never, never>>,
    'marketplace-wordpress-configure': RouteRecordInfo<'marketplace-wordpress-configure', '/marketplace/wordpress/configure', Record<never, never>, Record<never, never>>,
    'successcheckout': RouteRecordInfo<'successcheckout', '/successcheckout', Record<never, never>, Record<never, never>>,
    'unauthorized': RouteRecordInfo<'unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
    'xdao-app': RouteRecordInfo<'xdao-app', '/xdao-app', Record<never, never>, Record<never, never>>,
  }
}
