/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-global': RouteRecordInfo<'apps-global', '/apps/global', Record<never, never>, Record<never, never>>,
    'apps-local': RouteRecordInfo<'apps-local', '/apps/local', Record<never, never>, Record<never, never>>,
    'apps-manage-app-name': RouteRecordInfo<'apps-manage-app-name', '/apps/manage/:appName', { appName: ParamValue<true> }, { appName: ParamValue<false> }>,
    'apps-management': RouteRecordInfo<'apps-management', '/apps/management', Record<never, never>, Record<never, never>>,
    'dashboards-home': RouteRecordInfo<'dashboards-home', '/dashboards/home', Record<never, never>, Record<never, never>>,
    'dashboards-list': RouteRecordInfo<'dashboards-list', '/dashboards/list', Record<never, never>, Record<never, never>>,
    'dashboards-locations': RouteRecordInfo<'dashboards-locations', '/dashboards/locations', Record<never, never>, Record<never, never>>,
    'dashboards-overview': RouteRecordInfo<'dashboards-overview', '/dashboards/overview', Record<never, never>, Record<never, never>>,
    'dashboards-resources': RouteRecordInfo<'dashboards-resources', '/dashboards/resources', Record<never, never>, Record<never, never>>,
    'dashboards-rewards': RouteRecordInfo<'dashboards-rewards', '/dashboards/rewards', Record<never, never>, Record<never, never>>,
    'unauthorized': RouteRecordInfo<'unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
  }
}
